package de.CodingDev.BukkitAnalytics;

public enum BukkitAnalyticsEventType {
	//Don not rename! Only R3N3PDE has access to Rename!
	//START Version 1.2
	ASYNC_PLAYER_CHAT,
	BLOCK_BREAK,
	BLOCK_PLACE,
	DISTANCE_MOVED_IN_BOAT,
	DISTANCE_MOVED_IN_MINECART,
	DISTANCE_MOVED_IN_UNKNOW_VEHICLE,
	DISTANCE_MOVED_TOTAL,
	ENTITY_DAMAGE,
	ENTITY_DEATH,
	ENTITY_EXPLODE,
	ENTITY_REGAIN_HEALTH,
	ENTITY_TELEPORT,
	NOTE_PLAY,
	PLAYER_BED_ENTER,
	PLAYER_BUCKET_EMPTY,
	PLAYER_BUCKET_FILL,
	PLAYER_COMMAND,
	PLAYER_DAMAGE,
	PLAYER_DEATH,
	PLAYER_EXPLODE,
	PLAYER_DROP_ITEM,
	PLAYER_EGG_TRROW,
	PLAYER_FISH,
	PLAYER_JOIN,
	PLAYER_KICK,
	PLAYER_PICKUP_ITEM,
	PLAYER_QUIT,
	PLAYER_RESPAWN,
	PLAYER_TELEPORT,
	POTION_SPLASH,
	PROJECTILE_HIT,
	SERVER_LIST_PING;
	//END Version 1.2
}
